FROM maven:3.6.2-jdk-8 AS back-end-builder

WORKDIR /app

COPY . .

RUN mvn clean verify -DskipTests

FROM openjdk:8-jre-slim

WORKDIR /app

COPY --from=back-end-builder /app/target/tester-matching-1.0.0.jar /app/application.jar

CMD ["java", "-jar", "application.jar"]
